// Generated by CoffeeScript 1.6.3
var Anim;

Function.prototype.method = function(name, fn) {
  this.prototype[name] = fn;
  return this;
};

Anim = function() {};

Anim.method('start', function() {
  return this;
}).method('stop', function() {
  return this;
});
