// Generated by CoffeeScript 1.6.3
Book(function(isbn, title, author) {
  if (isbn === void 0) {
    throw new Error('book constructor requires an isbn');
  }
  this.isbn = isbn;
  this.title = title || 'no title specified';
});
