// Generated by CoffeeScript 1.6.3
var Carfactory, aodi, benchi, bmw;

switch (day) {
  case "Mon":
    go(work);
    break;
  case "Tue":
    go(relax);
    break;
  case "Thu":
    go(iceFishing);
    break;
  case "Fri":
  case "Sat":
    if (day === bingoDay) {
      go(bingo);
      go(dancing);
    }
    break;
  case "Sun":
    go(church);
    break;
  default:
    go(work);
}

benchi = function() {};

bmw = function() {};

aodi = function() {};

Carfactory = {
  createCar: function(brand) {
    var car;
    switch (brand) {
      case "benchi":
        car = new benchi();
        break;
      case "bmw":
        car = new bmw();
        break;
      case "aodi":
        car = new aodi();
        break;
      default:
        car = new car();
    }
  }
};
