// Generated by CoffeeScript 1.6.3
var box, sum, sum2;

box = function(num1, num2) {
  return num1 + num2;
};

sum = function(num1, num2) {
  return box.apply(this, [num1, num2]);
};

sum2 = function(num1, num2) {
  return box.call(this, num1, num2);
};

console.log(sum(10, 10));

console.log(sum2(20, 20));
