// Generated by CoffeeScript 1.6.3
var Car, dudu, tom;

Car = function(model, year, miles) {
  this.year = year;
  this.model = model;
  this.miles = miles;
};

Car.prototype.output = function() {
  return this.model + ' has gone ' + this.miles + 'km';
};

tom = new Car('jfeng', 2009, 2000);

console.log(tom.output());

dudu = new Car('dudu', 2010, 1000);

console.log(dudu.output());
