// Generated by CoffeeScript 1.6.3
/*
mySingle = 
  property1: "something1"
  property2: "something2"
  method1: ->
    console.log "singal method"
*/

/*
mySingle = ->
  privateVariable = 'something private'
  showProvate = ->
    console.log privateVariable
    return
  publicMethod: ->
    showProvate()
    return
  publicVar: 'the public can see this'

single = mySingle()
single.publicMethod()
console.log(single.publicVar)
*/

var Singleton;

Singleton = (function() {
  var init;
  init = function() {
    return {
      publicMethod: function() {
        console.log('hello world');
      },
      publicProperty: 'test'
    };
  };
  return {
    getInstance: function() {
      var instantiated;
      if (!instantiated) {
        instantiated = init();
      }
      return instantiated;
    }
  };
})();
