// Generated by CoffeeScript 1.7.1

/*
 * 是否自动滚动
 * 是否循环切换
 * 鼠标悬停停止切换
 * 页码
 * 翻页进度
 */
define(function(require, exports, module) {
  var $, Carousel;
  $ = require('jquery');
  Carousel = function(element, options) {
    this.element = element;
    this.options = options;
  };
  Carousel.prototype = {
    _start: function() {},
    _hover: function() {},
    init: function() {}
  };
  module.exports = Carousel;
});
