// Generated by CoffeeScript 1.7.1
var Books, Person, book, p;

Person = function(name, age) {
  this.name = name;
  this.age = age;
};

Books = function(title, name, age) {
  Person.call(this, name, age);
  this.title = title;
};

p = new Person("jack", 18);

book = new Books("book title");

console.log(book);
