// Generated by CoffeeScript 1.6.3
var infoBox, uploadBtn;

uploadBtn = document.getElementById('J_upload');

infoBox = document.getElementById('info');

uploadBtn.onchange = function(ev) {
  var file, fileInfo, files, _i, _len;
  files = ev.target.files;
  fileInfo = '';
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    fileInfo += '<p>' + file.name + '|' + file.size / 1024 + 'KB |' + file.type + '</p>';
  }
  infoBox.innerHTML = fileInfo;
};
