// Generated by CoffeeScript 1.6.3
var imgBox, infoBox, uploadBtn;

uploadBtn = document.getElementById('J_upload');

infoBox = document.getElementById('info');

imgBox = document.getElementById('imgshow');

uploadBtn.onchange = function(ev) {
  var file, fileInfo, files, imgShow, reader, _i, _len;
  files = ev.target.files;
  fileInfo = '';
  imgShow = '';
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    reader = new FileReader();
    fileInfo += '<p>' + file.name + '|' + file.size / 1024 + 'KB |' + file.type + '</p>';
    reader.readAsDataURL(file);
    reader.onload = function(e) {
      console.log(e.target.result);
      imgShow = document.createElement('img');
      imgShow.src = e.target.result;
      imgShow.width = 300;
      imgBox.appendChild(imgShow);
    };
  }
  infoBox.innerHTML = fileInfo;
};
