// Generated by CoffeeScript 1.6.3
var a, exports, func, fund, times,
  _this = this;

exports = this;

func = function() {
  return 'bar';
};

fund = function() {
  'bar';
};

times = function(a, b) {
  return a * b;
};

times = function(a, b) {
  if (a == null) {
    a = 1;
  }
  if (b == null) {
    b = 2;
  }
  return a * b;
};

a = "hello";

alert(a);

alert(a);

alert(inspect(a));

alert(inspect(a));

alert(inspect(a));

this.clickHandler = function() {
  return alert("clicked");
};

dlement.addEventListener('click', function(e) {
  return _this.clickHandler(e);
});
