// Generated by CoffeeScript 1.6.3
$(function($) {
  var allBox, listBox, listBoxCheck;
  allBox = $('#J_All');
  listBox = $('.list input[type=checkbox]');
  allBox.delegate(this, 'change', function() {
    if ($(this).prop('checked')) {
      listBox.attr('checked', true);
    } else {
      listBox.attr('checked', false);
    }
  });
  listBoxCheck = function() {
    $.each(listBox, function(){
      console.log(listBox);
      if($(this).prop('checked')){
        return true
      } else {
        return false
      }
    });
  };
  listBoxCheck();
});
